<?php
declare(strict_types=1);
require_once __DIR__.'/_common.php';
require_once __DIR__.'/../inspections/_common.php';
require_login();
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);
$s=db()->prepare('SELECT ct.*,e.first_name,e.last_name FROM checkout_transactions ct INNER JOIN employees e ON e.id=ct.employee_id WHERE ct.id=?');$s->execute([$id]);$transaction=$s->fetch();if(!is_array($transaction)){http_response_code(404);exit('Transaction not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$itemId=filter_input(INPUT_POST,'item_id',FILTER_VALIDATE_INT);$s=db()->prepare('SELECT ci.*,t.name FROM checkout_items ci INNER JOIN tools t ON t.id=ci.tool_id WHERE ci.id=? AND ci.transaction_id=? AND ci.return_status="Pending"');$s->execute([$itemId,$id]);$item=$s->fetch();if(!is_array($item)){flash('danger','Item not found or already returned.');redirect('/checkout/return.php?id='.$id);} $url=inspection_create_queue('Checkin',[['type'=>'Checkin','tool_id'=>(int)$item['tool_id'],'transaction_id'=>(int)$id,'checkout_item_id'=>(int)$item['id'],'employee_id'=>(int)$transaction['employee_id']]],BASE_URL.'/checkout/return.php?id='.$id);redirect($url);}
$items=db()->prepare('SELECT ci.*,t.name,t.internal_id FROM checkout_items ci INNER JOIN tools t ON t.id=ci.tool_id WHERE ci.transaction_id=? ORDER BY ci.return_status="Pending" DESC,t.name');$items->execute([$id]);$items=$items->fetchAll();$pageTitle='Return Tools';require __DIR__.'/../includes/header.php';?>
<h1>Return Tools</h1><div class="muted"><?=e((string)$transaction['transaction_number'])?> — <?=e((string)$transaction['first_name'].' '.(string)$transaction['last_name'])?></div>
<?php foreach($items as $item):?><div class="card"><h2><?=e((string)$item['name'])?></h2><p><strong>ID:</strong> <?=e((string)$item['internal_id'])?> | <strong>Checkout Condition:</strong> <?=e((string)$item['checkout_condition'])?></p><?php if($item['return_status']!=='Pending'):?><div class="alert success">Returned as <?=e((string)$item['return_status'])?> with condition <?=e((string)$item['return_condition'])?>.</div><?php else:?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="item_id" value="<?=(int)$item['id']?>"><button class="btn">Start Required Check-In Inspection</button></form><?php endif;?></div><?php endforeach;?>
<?php require __DIR__.'/../includes/footer.php';?>
